name: Deploy dbt Model to PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-snowflake

    - name: Configure dbt profile
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml <<EOL
        my_dbt_profile:
          target: prod
          outputs:
            prod:
              type: snowflake
              account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
              user: ${{ secrets.SNOWFLAKE_USER }}
              password: ${{ secrets.SNOWFLAKE_PASSWORD }}
              role: ${{ secrets.SNOWFLAKE_ROLE }}
              database: ${{ secrets.SNOWFLAKE_DATABASE }}
              warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
              schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
              threads: 4
              client_session_keep_alive: False
        EOL

    - name: Run dbt deps
      run: dbt deps

    - name: Run dbt build for single model
      run: dbt build --select stg_listing
